# Generated by Django 4.0.5 on 2022-06-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20, verbose_name='Site')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'RSS resources',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='News Title')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='News Summary')),
                ('published_at', models.DateTimeField(null=True, verbose_name='Publiched Date')),
                ('rss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='rss.rss', verbose_name='News')),
            ],
            options={
                'verbose_name_plural': 'News list',
            },
        ),
    ]
